### ISSUE TITLE
Crash on Startup in v0.5 (1.20.6) / v0.4 works fine in 1.20.6

### ISSUE THREAD

**Issue by VincPlyz** [godkyo98/AFKFish#1]
[18:40:26] [main/ERROR]:
 Mixin apply for mod autofish failed autofish.mixins.json:MixinFishHookEntity from mod autofish -> net.minecraft.class_1536: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException Critical injection failure: @Inject annotation on tickFishingLogic could not find any targets matching 'tickFishingLogic' in net.minecraft.class_1536. No refMap loaded. [PREINJECT Applicator Phase -> autofish.mixins.json:MixinFishHookEntity from mod autofish -> Prepare Injections ->  -> handler$zzh000$autofish$tickFishingLogic(Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: @Inject annotation on tickFishingLogic could not find any targets matching 'tickFishingLogic' in net.minecraft.class_1536. No refMap loaded. [PREINJECT Applicator Phase -> autofish.mixins.json:MixinFishHookEntity from mod autofish -> Prepare Injections ->  -> handler$zzh000$autofish$tickFishingLogic(Lnet/minecraft/class_2338;Lorg/spongepowered/asm/mixin/injection/callback/CallbackInfo;)V -> Parse]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.validateTargets(InjectionInfo.java:658) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.findTargets(InjectionInfo.java:589) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.readAnnotation(InjectionInfo.java:330) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:316) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.<init>(InjectionInfo.java:308) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.CallbackInjectionInfo.<init>(CallbackInjectionInfo.java:46) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at java.base/jdk.internal.reflect.DirectConstructorHandleAccessor.newInstance(DirectConstructorHandleAccessor.java:62) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:502) ~[?:?]
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:486) ~[?:?]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo$InjectorEntry.create(InjectionInfo.java:149) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.parse(InjectionInfo.java:710) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.prepareInjections(MixinTargetContext.java:1329) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.prepareInjections(MixinApplicatorStandard.java:1053) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:327) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:422) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403) ~[sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202) [sponge-mixin-0.13.3+mixin.0.8.5.jar:0.13.3+mixin.0.8.5]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:422) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) [fabric-loader-0.15.11.jar:?]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) [?:?]
	at net.minecraft.class_1299.<clinit>(class_1299.java:323) [client-intermediary.jar:?]
	at net.minecraft.class_1802.<clinit>(class_1802.java:855) [client-intermediary.jar:?]
	at net.minecraft.class_6089.method_9530(class_6089.java:64) [client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26172(class_4970.java:1057) [client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26218(class_4970.java:1053) [client-intermediary.jar:?]
	at net.minecraft.class_4970.method_9549(class_4970.java:356) [client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971$class_3752.<init>(class_4970.java:1336) [client-intermediary.jar:?]
	at net.minecraft.class_4970$class_4971.method_26200(class_4970.java:868) [client-intermediary.jar:?]
	at net.minecraft.class_2246.<clinit>(class_2246.java:1260) [client-intermediary.jar:?]
	at net.minecraft.class_2358.method_10199(class_2358.java:336) [client-intermediary.jar:?]
	at net.minecraft.class_2966.method_12851(class_2966.java:53) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:170) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]
[18:40:27] [main/WARN]:
 Failed to get system info for GL Caps
java.lang.IllegalStateException: Rendersystem called from wrong thread
	at com.mojang.blaze3d.systems.RenderSystem.constructThreadException(RenderSystem.java:183) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.assertOnRenderThread(RenderSystem.java:172) ~[client-intermediary.jar:?]
	at com.mojang.blaze3d.systems.RenderSystem.getCapsString(RenderSystem.java:872) ~[client-intermediary.jar:?]
	at net.minecraft.class_6396.method_37123(class_6396.java:66) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_37274(class_310.java:2593) [client-intermediary.jar:?]
	at net.minecraft.class_310.method_22681(class_310.java:2564) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:178) [client-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.15.11.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.15.11.jar:?]

**Comment by godkyo98** [comment]
Specifically, have you downloaded any additional mods? Version 0.4 is for 1.20.5, and version 0.5 is for 1.20.6. Currently I only work for Fabric

**Comment by godkyo98** [comment]
![Screenshot 2024-05-06 001444](https://github.com/godkyo98/AFKFish/assets/45629767/f808b27c-8c7a-4b09-b85d-7f790bc0e301)
Works quite well

**Comment by VincPlyz** [comment]
My Mod List

<img width="559" alt="image" src="https://github.com/godkyo98/AFKFish/assets/105316565/e8abc38e-734f-4317-b609-0f512e3f4fa8">

**Comment by godkyo98** [comment]
For 0.4, use version 1.20.5, bro, but 0.5 cannot run in 1.20.5, and thank you for reporting the error in version 0.5 to me. Currently, testing with code is very good, but testing with downloaded files has a very virtual mixis error

**Comment by godkyo98** [comment]
Bro is fix this. But 0.5 run in >1.20.6. This my bad to set version :(((. You need use 0.4 to 1.20.6. Thank, you rq my problem
